# Generated by Django 5.0.1 on 2024-02-11 04:48

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_variantname_variantvalue_variant_productvariant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=products.models.upload_Prodcut_image),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product images",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
    ]
