# Generated by Django 5.0.1 on 2024-02-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
